### ISSUE TITLE
travis, add windows env support

### ISSUE THREAD

**Issue by iTaa** [chinapnr/fishbase#131]
add windows env support

example：
``` yaml

matrix:
  include:
    - os: linux
      python:
        - "nightly"
        - "3.8-dev"
        - "pypy3.5"
        - "3.7"
        - "3.6"
        - "3.5"
        - "3.4"
        - "2.7"
    - os: windows
      python:
        - "nightly"
        - "3.8-dev"
        - "pypy3.5"
        - "3.7"
        - "3.6"
        - "3.5"
        - "3.4"
        - "2.7"
```
